baseURL = 'https://www.correct-connect.jp'
locale = 'ja'
title = 'コレクトコネクト｜組版・校正・Web制作'
theme = 'hugo-texify'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  customCSS = ["css/custom.css"]